# Generated by Django 3.1.5 on 2021-05-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='achievements',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='workExp',
            field=models.TextField(null=True),
        ),
    ]
