# Generated by Django 3.1.5 on 2021-05-14 20:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210514_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='workExp',
        ),
        migrations.AddField(
            model_name='resume',
            name='workExperience',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='achievements',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projects',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
