# Generated by Django 3.1.5 on 2021-05-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210514_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('BT', 'Bio Technology'), ('che', 'Chemical'), ('chem', 'Chemistry'), ('civil', 'Civil'), ('cse', 'Computer Science'), ('elec', 'Electrical'), ('ece', 'Electronics and Communication'), ('ipe', 'Industial and Production'), ('it', 'Information Technology'), ('ice', 'Instrumentation and Control'), ('maths', 'Mathematics'), ('phe', 'Physics'), ('tt', 'Texttile Technology')], default='cse', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('BTech', 'Btech'), ('Mtech', 'Mtech')], default='Btech', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='rollNumber',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=2017),
        ),
    ]
