# Generated by Django 3.1.5 on 2021-05-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210515_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('BTech', 'BTech'), ('MTech', 'MTech')], default='BTech', max_length=5),
        ),
    ]
