# Generated by Django 3.1.5 on 2021-05-15 07:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_auto_20210515_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='programEligible',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BTech', 'BTech'), ('MTech', 'MTech')], default='BTech', max_length=11),
        ),
    ]
