# Generated by Django 3.1.5 on 2021-05-15 08:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_auto_20210515_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='departmentsEligible',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bio Technology', 'Bio Technology'), ('Chemical', 'Chemical'), ('Chemistry', 'Chemistry'), ('Civil', 'Civil'), ('Computer Science', 'Computer Science'), ('Electrical', 'Electrical'), ('Electronics and Communication', 'Electronics and Communication'), ('Industial and Production', 'Industial and Production'), ('Information Technology', 'Information Technology'), ('Instrumentation and Control', 'Instrumentation and Control'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Texttile Technology', 'Texttile Technology')], default='Computer Science', max_length=213),
        ),
        migrations.AlterField(
            model_name='company',
            name='employmentType',
            field=models.CharField(blank=True, choices=[('Internship', 'Internship'), ('Full Time', 'Full Time')], max_length=200, null=True),
        ),
    ]
