# Generated by Django 3.1.5 on 2021-05-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0004_auto_20210515_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
