# Generated by Django 3.1.5 on 2021-05-15 15:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0005_auto_20210515_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='JobDescription',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
